"""add transfer idempotency metadata

Revision ID: abda05ca9bcb
Revises: f270871c0688
Create Date: 2026-09-28 02:42:20.234775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abda05ca9bcb'
down_revision: Union[str, Sequence[str], None] = 'f270871c0688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('transfers', sa.Column('request_hash', sa.String(length=64), nullable=True))
    op.create_check_constraint('ck_transfers_idempotency_pair', 'transfers', '(idempotency_key IS NULL) = (request_hash IS NULL)')
    op.create_unique_constraint('uq_transfers_idempotency_key', 'transfers', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transfers_idempotency_key', 'transfers', type_='unique')
    op.drop_constraint('ck_transfers_idempotency_pair', 'transfers', type_='check')
    op.drop_column('transfers', 'request_hash')
    op.drop_column('transfers', 'idempotency_key')
    # ### end Alembic commands ###
