"""align account history index

Revision ID: bfd4b6a9dc84
Revises: abda05ca9bcb
Create Date: 2026-09-28 03:10:32.298070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd4b6a9dc84'
down_revision: Union[str, Sequence[str], None] = 'abda05ca9bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_transactions_account_id_created_at_desc'), table_name='account_transactions')
    op.drop_index(op.f('ix_account_transactions_transfer_id'), table_name='account_transactions')
    op.create_index('ix_account_transactions_account_id_created_at_id_desc', 'account_transactions', ['account_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_transactions_account_id_created_at_id_desc', table_name='account_transactions')
    op.create_index(op.f('ix_account_transactions_transfer_id'), 'account_transactions', ['transfer_id'], unique=False)
    op.create_index(op.f('ix_account_transactions_account_id_created_at_desc'), 'account_transactions', ['account_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
