"""initial schema

Revision ID: f270871c0688
Revises: 
Create Date: 2026-09-28 01:14:24.437696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f270871c0688'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_accounts_balance_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_account_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_account_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_transfers_amount_positive'),
    sa.CheckConstraint('source_account_id <> destination_account_id', name='ck_transfers_distinct_accounts'),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfers_destination_account_id', 'transfers', ['destination_account_id'], unique=False)
    op.create_index('ix_transfers_source_account_id', 'transfers', ['source_account_id'], unique=False)
    op.create_table('account_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('transfer_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('debit', 'credit')", name='ck_account_transactions_direction'),
    sa.CheckConstraint('amount > 0', name='ck_account_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', 'direction', name='uq_account_transactions_transfer_direction')
    )
    op.create_index('ix_account_transactions_account_id_created_at_desc', 'account_transactions', ['account_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_account_transactions_transfer_id', 'account_transactions', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_transactions_transfer_id', table_name='account_transactions')
    op.drop_index('ix_account_transactions_account_id_created_at_desc', table_name='account_transactions')
    op.drop_table('account_transactions')
    op.drop_index('ix_transfers_source_account_id', table_name='transfers')
    op.drop_index('ix_transfers_destination_account_id', table_name='transfers')
    op.drop_table('transfers')
    op.drop_table('accounts')
    # ### end Alembic commands ###
